apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file codeserver.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: code-server
  name: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file codeserver.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: code-server
    spec:
      initContainers:
        - image: alpine:latest
          name: alpine
          command: ["/bin/sh"]
          args:
            - -c
            - |
              mkdir -p /config/workspace
              chown 1000:1000 /config/workspace
          volumeMounts:
            - mountPath: /config
              name: code-server-claim0
        - image: alpine/git:latest
          name: alpine-git
          command: ["/bin/sh"]
          args:
            - -c
            - |
              cd /config/workspace
              git clone https://github.com/tbd-with-pallete/web-example.git
          volumeMounts:
            - mountPath: /config
              name: code-server-claim0
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      containers:
        - image: node:lts
          name: node
          command: ["/bin/sh"]
          args: ["-c", "cd /config/workspace/web-example/src/web-example && npm i && npm run dev -- --host "]
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: code-server-claim0
        - env:
            - name: DEFAULT_WORKSPACE
              value: /config/workspace
            - name: HASHED_PASSWORD
            - name: PASSWORD
              value: password
            - name: PGID
              value: "1000"
            - name: PROXY_DOMAIN
              value: code-server.local
            - name: PUID
              value: "1000"
            - name: SUDO_PASSWORD
              value: password
            - name: SUDO_PASSWORD_HASH
            - name: TZ
              value: "America/New_York"
            - name: GITHUB_TOKEN
              value: "{{.spectro.macro.github_token}}"
          image: lscr.io/linuxserver/code-server:latest
          name: code-server
          ports:
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: code-server-claim0
      restartPolicy: Always
      volumes:
        - name: code-server-claim0
          persistentVolumeClaim:
            claimName: code-server-claim0
